### ISSUE TITLE
Slight namespace clashwith Boom package on CRAN

### ISSUE THREAD

**Issue by technocrat** [moodymudskipper/boom#4]
There's CRAN package named Boom, with a capital B. Too late to change this new must-have package to boomer, which is still available?

**Comment by moodymudskipper** [comment]
No not too late, it's the plan :). I made a silly mistake, I'm working on a few features and I'll release the bettered boom as boomer.

I think boom can be used in parallel if it's installed in another library folder than Boom, but not ideal I understand...

**Comment by moodymudskipper** [comment]
@technocrat enjoy! https://moodymudskipper.github.io/boomer/index.html
